# Generated by Django 5.2 on 2026-05-23 11:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('OFFICIAL_LETTER', 'Official Letter'), ('MEMORANDUM', 'Memorandum'), ('OFFICE_ORDER', 'Office Order'), ('CIRCULAR', 'Circular / Notice'), ('ENDORSEMENT', 'Endorsement'), ('CERTIFICATE', 'Certificate'), ('MEETING_RECORD', 'Meeting Agenda / Minutes'), ('SHOW_CAUSE', 'Show Cause / Explanation Letter')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('UNDER_APPROVAL', 'Under Approval'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('ARCHIVED', 'Archived'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=20)),
                ('classification', models.CharField(blank=True, max_length=40)),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('originator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docgen_originated_documents', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_documents', to='DocGen.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentQRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('signed_payload', models.TextField(blank=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_token', to='DocGen.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=160)),
                ('actor_type', models.CharField(choices=[('USER', 'Named User'), ('ROLE', 'Role'), ('POSITION', 'Position'), ('DYNAMIC', 'Dynamic')], max_length=20)),
                ('actor_value', models.CharField(max_length=255)),
                ('required_action', models.CharField(choices=[('REVIEW', 'Review'), ('ENDORSE', 'Endorse'), ('APPROVE', 'Approve'), ('APPROVE_WITH_COMMENTS', 'Approve With Comments'), ('RETURN', 'Return for Correction'), ('REJECT', 'Reject'), ('DELEGATE', 'Delegate'), ('REQUEST_CLARIFICATION', 'Request Clarification')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('UNDER_APPROVAL', 'Under Approval'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('ARCHIVED', 'Archived'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='UNDER_REVIEW', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docgen_workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='DocGen.document')),
            ],
            options={
                'ordering': ['stage_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('doc_type_code', models.CharField(max_length=20)),
                ('current_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('year', 'doc_type_code'), name='uniq_docgen_ref_sequence_year_type')],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='DocGen.templatecategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('layout_schema', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docgen_created_template_revisions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='DocGen.template')),
            ],
            options={
                'ordering': ['template', '-version'],
            },
        ),
        migrations.CreateModel(
            name='TemplatePlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=180)),
                ('field_type', models.CharField(choices=[('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text'), ('DATE', 'Date'), ('NUMBER', 'Number'), ('CURRENCY', 'Currency'), ('DROPDOWN', 'Dropdown'), ('USER_LOOKUP', 'User Lookup'), ('DEPARTMENT_LOOKUP', 'Department Lookup'), ('TABLE', 'Table'), ('SIGNATURE', 'Signature'), ('REFERENCE_NUMBER', 'Reference Number'), ('ATTACHMENT_LINK', 'Attachment Link'), ('CONDITIONAL_BLOCK', 'Conditional Block')], max_length=40)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='DocGen.templaterevision')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='template_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='DocGen.templaterevision'),
        ),
        migrations.CreateModel(
            name='TemplateWorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=160)),
                ('mode', models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('PARALLEL_ALL', 'Parallel (All Must Act)'), ('PARALLEL_ANY', 'Parallel (Any One Can Act)')], default='SEQUENTIAL', max_length=20)),
                ('actor_type', models.CharField(choices=[('USER', 'Named User'), ('ROLE', 'Role'), ('POSITION', 'Position'), ('DYNAMIC', 'Dynamic')], max_length=20)),
                ('actor_value', models.CharField(max_length=255)),
                ('required_action', models.CharField(choices=[('REVIEW', 'Review'), ('ENDORSE', 'Endorse'), ('APPROVE', 'Approve'), ('APPROVE_WITH_COMMENTS', 'Approve With Comments'), ('RETURN', 'Return for Correction'), ('REJECT', 'Reject'), ('DELEGATE', 'Delegate'), ('REQUEST_CLARIFICATION', 'Request Clarification')], default='REVIEW', max_length=30)),
                ('sla_hours', models.PositiveIntegerField(default=48)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='DocGen.templaterevision')),
            ],
            options={
                'ordering': ['stage_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placeholder_name', models.CharField(max_length=100)),
                ('value_text', models.TextField(blank=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='DocGen.document')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'placeholder_name'), name='uniq_docgen_document_placeholder_value')],
            },
        ),
        migrations.CreateModel(
            name='DocumentPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('file', models.FileField(upload_to='docgen/pdfs/%Y/%m/')),
                ('sha256_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_versions', to='DocGen.document')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docgen_generated_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document', '-version'],
                'constraints': [models.UniqueConstraint(fields=('document', 'version'), name='uniq_docgen_pdf_version')],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docgen_created_document_revisions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='DocGen.document')),
            ],
            options={
                'ordering': ['document', '-version'],
                'constraints': [models.UniqueConstraint(fields=('document', 'version'), name='uniq_docgen_document_revision_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='templaterevision',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='uniq_docgen_template_revision_version'),
        ),
        migrations.AddConstraint(
            model_name='templateplaceholder',
            constraint=models.UniqueConstraint(fields=('revision', 'name'), name='uniq_docgen_placeholder_name_per_revision'),
        ),
        migrations.AddConstraint(
            model_name='templateworkflowstage',
            constraint=models.UniqueConstraint(fields=('revision', 'stage_order'), name='uniq_docgen_workflow_stage_order'),
        ),
    ]
