# Generated by Django 5.2 on 2026-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocGen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentworkflowstage',
            name='execution_mode',
            field=models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('PARALLEL_ALL', 'Parallel (All Must Act)'), ('PARALLEL_ANY', 'Parallel (Any One Can Act)')], default='SEQUENTIAL', max_length=20),
        ),
    ]
