# Generated by Django 5.2 on 2026-05-23 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DocGen", "0002_documentworkflowstage_execution_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="default", max_length=80, unique=True)),
                (
                    "archive_retention_days",
                    models.PositiveIntegerField(default=365, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_active", "name"],
            },
        ),
    ]
