# Generated by Django 5.2 on 2026-05-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DocGen", "0003_document_archived_at_retentionpolicy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="template",
            options={
                "ordering": ["title"],
                "permissions": [
                    ("template_author", "Can author DocGen templates"),
                    ("template_publisher", "Can publish and retire DocGen templates"),
                    ("admin", "Can administer DocGen operations"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("originator", "Can create and submit DocGen documents"),
                    ("reviewer", "Can review DocGen workflow stages"),
                    ("approver", "Can approve and finalize DocGen documents"),
                ],
            },
        ),
    ]
