# Generated by Django 5.2 on 2026-05-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DocGen", "0004_formal_rbac_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentworkflowstage",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentworkflowstage",
            name="escalation_level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="documentworkflowstage",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
