# Generated by Django 5.2 on 2026-05-24 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocGen', '0009_template_token_audit_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['title'], 'permissions': [('template_author', 'Can author DocGen templates'), ('template_publisher', 'Can publish and retire DocGen templates'), ('admin', 'Can administer DocGen operations'), ('viewer', 'Can view finalized DocGen documents')]},
        ),
        migrations.AddField(
            model_name='retentionpolicy',
            name='document_type',
            field=models.CharField(blank=True, choices=[('OFFICIAL_LETTER', 'Official Letter'), ('MEMORANDUM', 'Memorandum'), ('OFFICE_ORDER', 'Office Order'), ('CIRCULAR', 'Circular / Notice'), ('ENDORSEMENT', 'Endorsement'), ('CERTIFICATE', 'Certificate'), ('MEETING_RECORD', 'Meeting Agenda / Minutes'), ('SHOW_CAUSE', 'Show Cause / Explanation Letter')], help_text='If set, this policy applies only to the specified document type. Leave blank for a global policy.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='templateworkflowstage',
            name='branch_condition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TemplateAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('LOGO', 'Logo'), ('WATERMARK', 'Watermark'), ('LETTERHEAD', 'Letterhead')], max_length=20)),
                ('file', models.FileField(upload_to='docgen/template_assets/')),
                ('label', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='DocGen.templaterevision')),
            ],
            options={
                'ordering': ['asset_type', 'label'],
            },
        ),
    ]
