# pyright: reportAttributeAccessIssue=false

import base64
from io import BytesIO
import hashlib
import json

from django.conf import settings
from django.core.files.base import ContentFile
from django.core.exceptions import ValidationError
from django.db import transaction
from django.utils import timezone
from django.utils.html import escape
from django.utils.module_loading import import_string
from datetime import timedelta
from xhtml2pdf import pisa

from .adapters import LocalActorResolutionAdapter
from .models import Document, DocumentPDF, DocumentStatus, DocumentWorkflowStage
from .notifications import LocalNotificationAdapter


def _generate_qr_data_uri(data: str) -> str | None:
    """Return a base64 PNG data URI for a QR code, or None if qrcode is not installed."""
    try:
        import qrcode  # type: ignore[import]
        from PIL import Image  # type: ignore[import]
    except ImportError:
        return None
    img = qrcode.make(data)
    buf = BytesIO()
    img.save(buf, format="PNG")
    encoded = base64.b64encode(buf.getvalue()).decode("ascii")
    return f"data:image/png;base64,{encoded}"


def _build_pdf_html(document: Document) -> str:
    fields = [
        {
            "placeholder_name": field.placeholder_name,
            "value_text": field.value_text,
            "value_json": field.value_json,
        }
        for field in document.fields.order_by("placeholder_name")
    ]
    rows = []
    for field in fields:
        value_text = field.get("value_text")
        value_json = field.get("value_json")
        rendered_value = value_text if value_text not in [None, ""] else json.dumps(value_json, ensure_ascii=True)
        rows.append(
            "<tr>"
            f"<td>{escape(field.get('placeholder_name') or '')}</td>"
            f"<td>{escape(rendered_value)}</td>"
            "</tr>"
        )

    events = (document.metadata or {}).get("events", [])
    event_items = [
        "<li>"
        f"{escape(event.get('timestamp', ''))}"
        f" - {escape(event.get('action', ''))}"
        f" ({escape(event.get('actor', 'system') or 'system')})"
        "</li>"
        for event in events[-10:]
    ]

    finalized_at = document.finalized_at.isoformat() if document.finalized_at else ""

    # QR code block — embed image if token exists and qrcode library is available
    qr_html = ""
    try:
        qr_token = document.qr_token  # OneToOne; raises if absent
        verify_path = f"/compass/docgen/verify/{qr_token.token}/"
        verify_url = getattr(settings, "DOCGEN_PUBLIC_BASE_URL", "").rstrip("/") + verify_path
        qr_data_uri = _generate_qr_data_uri(verify_url)
        if qr_data_uri:
            qr_html = (
                "<div style='margin-top:24px;text-align:center;'>"
                f"<img src='{qr_data_uri}' width='100' height='100' />"
                "<br/><span style='font-size:8pt;color:#555;'>"
                f"Scan to verify: {escape(verify_url)}"
                "</span></div>"
            )
        else:
            qr_html = f"<p class='small'>Verify: {escape(verify_url)}</p>"
    except Exception:
        pass

    return f"""
<!DOCTYPE html>
<html>
    <head>
        <meta charset=\"utf-8\" />
        <style>
            body {{ font-family: Helvetica, Arial, sans-serif; font-size: 11pt; color: #111; }}
            h1 {{ font-size: 18pt; margin-bottom: 4px; }}
            h2 {{ font-size: 12pt; margin-top: 18px; margin-bottom: 6px; }}
            .meta {{ margin: 2px 0; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
            th, td {{ border: 1px solid #bbb; padding: 6px; text-align: left; vertical-align: top; }}
            th {{ background: #f3f3f3; }}
            .small {{ color: #666; font-size: 9pt; }}
        </style>
    </head>
    <body>
        <h1>{escape(document.title)}</h1>
        <div class=\"meta\"><strong>Reference:</strong> {escape(document.reference_number or '')}</div>
        <div class=\"meta\"><strong>Type:</strong> {escape(document.document_type)}</div>
        <div class=\"meta\"><strong>Subject:</strong> {escape(document.subject or '')}</div>
        <div class=\"meta\"><strong>Status:</strong> {escape(document.status)}</div>
        <div class=\"meta\"><strong>Finalized At:</strong> {escape(finalized_at)}</div>

        <h2>Field Values</h2>
        <table>
            <thead>
                <tr><th>Placeholder</th><th>Value</th></tr>
            </thead>
            <tbody>
                {''.join(rows) if rows else '<tr><td colspan="2">No fields captured.</td></tr>'}
            </tbody>
        </table>

        <h2>Recent Workflow Events</h2>
        <ul>
            {''.join(event_items) if event_items else '<li>No events recorded.</li>'}
        </ul>

        {qr_html}

        <p class=\"small\">Generated by DocGen on {escape(timezone.now().isoformat())}</p>
    </body>
</html>
""".strip()


def _render_html_to_pdf_bytes(html: str) -> bytes:
    output = BytesIO()
    render_result = pisa.CreatePDF(src=html, dest=output, encoding="utf-8")
    if render_result.err:
        raise ValidationError("PDF rendering failed.")
    return output.getvalue()


def generate_pdf_artifact(document: Document, generated_by=None) -> DocumentPDF:
    html = _build_pdf_html(document)
    content = _render_html_to_pdf_bytes(html)
    sha256_hash = hashlib.sha256(content).hexdigest()

    latest = document.pdf_versions.order_by("-version").first()
    next_version = 1 if latest is None else latest.version + 1

    document.pdf_versions.filter(is_active=True).update(is_active=False)
    pdf = DocumentPDF(
        document=document,
        version=next_version,
        sha256_hash=sha256_hash,
        is_active=True,
        generated_by=generated_by,
    )
    timestamp = timezone.now().strftime("%Y%m%d%H%M%S")
    filename = f"{document.reference_number or document.pk}_v{next_version}_{timestamp}.pdf"
    pdf.file.save(filename, ContentFile(content), save=False)
    pdf.save()
    return pdf


def generate_pdf_artifact_stub(document: Document, generated_by=None) -> DocumentPDF:
    # Backward-compatible alias for callers not yet updated.
    return generate_pdf_artifact(document=document, generated_by=generated_by)


def generate_pdf_preview(document: Document) -> bytes:
    """Return a DRAFT-watermarked PDF as raw bytes without saving any artifact."""
    html = _build_pdf_preview_html(document)
    return _render_html_to_pdf_bytes(html)


def _build_pdf_preview_html(document: Document) -> str:
    """Same as _build_pdf_html but injects a DRAFT watermark style."""
    base = _build_pdf_html(document)
    watermark_style = (
        "<style>"
        "body::before {"
        "  content: 'DRAFT';"
        "  position: fixed;"
        "  top: 40%;"
        "  left: 10%;"
        "  font-size: 90pt;"
        "  color: rgba(200,0,0,0.12);"
        "  transform: rotate(-35deg);"
        "  z-index: -1;"
        "  pointer-events: none;"
        "}"
        "</style>"
    )
    return base.replace("</head>", watermark_style + "</head>", 1)


def _get_actor_resolution_adapter():
    adapter_path = getattr(
        settings,
        "DOCGEN_ACTOR_RESOLUTION_ADAPTER",
        "DocGen.adapters.LocalActorResolutionAdapter",
    )
    try:
        adapter_cls = import_string(adapter_path)
        adapter = adapter_cls()
    except Exception:
        adapter = LocalActorResolutionAdapter()

    if not hasattr(adapter, "resolve"):
        return LocalActorResolutionAdapter()
    return adapter


def resolve_workflow_actor(actor_type: str, actor_value: str, document: Document) -> str:
    adapter = _get_actor_resolution_adapter()
    resolved = adapter.resolve(actor_type=actor_type, actor_value=actor_value, document=document)
    if isinstance(resolved, str) and resolved:
        return resolved
    return LocalActorResolutionAdapter().resolve(actor_type=actor_type, actor_value=actor_value, document=document)


def _get_notification_adapter():
    adapter_path = getattr(
        settings,
        "DOCGEN_NOTIFICATION_ADAPTER",
        "DocGen.notifications.LocalNotificationAdapter",
    )
    try:
        adapter_cls = import_string(adapter_path)
        adapter = adapter_cls()
    except Exception:
        adapter = LocalNotificationAdapter()

    if not hasattr(adapter, "publish"):
        return LocalNotificationAdapter()
    return adapter


def emit_notification_event(event_type: str, payload: dict) -> bool:
    adapter = _get_notification_adapter()
    try:
        return bool(adapter.publish(event_type=event_type, payload=payload))
    except Exception:
        return False


def _append_system_event(document: Document, action: str, comment: str, now=None):
    current_time = now or timezone.now()
    metadata = document.metadata or {}
    events = metadata.get("events", [])
    events.append(
        {
            "action": action,
            "actor": None,
            "comment": comment,
            "timestamp": current_time.isoformat(),
        }
    )
    metadata["events"] = events
    document.metadata = metadata


def process_sla_events(now=None) -> dict[str, int]:
    current_time = now or timezone.now()
    reminder_minutes = int(getattr(settings, "DOCGEN_SLA_REMINDER_MINUTES_BEFORE_DUE", 60))
    escalation_minutes = int(getattr(settings, "DOCGEN_SLA_ESCALATION_MINUTES_AFTER_DUE", 120))

    reminder_cutoff_delta = timedelta(minutes=max(0, reminder_minutes))
    escalation_cutoff_delta = timedelta(minutes=max(0, escalation_minutes))

    active_stages = DocumentWorkflowStage.objects.select_related("document").filter(
        status__in=[DocumentStatus.UNDER_REVIEW, DocumentStatus.UNDER_APPROVAL],
        due_at__isnull=False,
    )

    reminders_sent = 0
    escalations_sent = 0
    notifications_sent = 0
    notification_failures = 0

    for stage in active_stages:
        due_at = stage.due_at
        if due_at is None:
            continue

        document_updated = False
        stage_updated_fields = []

        if stage.reminder_sent_at is None:
            reminder_start = due_at - reminder_cutoff_delta
            if reminder_start <= current_time < due_at:
                reminder_payload = {
                    "document_id": stage.document_id,
                    "reference_number": stage.document.reference_number,
                    "stage_id": stage.id,
                    "stage_order": stage.stage_order,
                    "required_action": stage.required_action,
                    "actor_value": stage.actor_value,
                    "due_at": due_at.isoformat(),
                }
                _append_system_event(
                    stage.document,
                    action="sla_reminder",
                    comment=f"Stage {stage.id} due at {due_at.isoformat()}",
                    now=current_time,
                )
                if emit_notification_event("docgen.stage.sla_reminder", reminder_payload):
                    notifications_sent += 1
                else:
                    notification_failures += 1
                stage.reminder_sent_at = current_time
                stage_updated_fields.extend(["reminder_sent_at", "updated_at"])
                reminders_sent += 1
                document_updated = True

        if stage.escalated_at is None and current_time >= (due_at + escalation_cutoff_delta):
            escalation_payload = {
                "document_id": stage.document_id,
                "reference_number": stage.document.reference_number,
                "stage_id": stage.id,
                "stage_order": stage.stage_order,
                "required_action": stage.required_action,
                "actor_value": stage.actor_value,
                "due_at": due_at.isoformat(),
                "overdue_minutes": int((current_time - due_at).total_seconds() // 60),
            }
            _append_system_event(
                stage.document,
                action="sla_escalation",
                comment=f"Stage {stage.id} overdue since {due_at.isoformat()}",
                now=current_time,
            )
            if emit_notification_event("docgen.stage.sla_escalation", escalation_payload):
                notifications_sent += 1
            else:
                notification_failures += 1
            stage.escalated_at = current_time
            stage.escalation_level = (stage.escalation_level or 0) + 1
            if "updated_at" not in stage_updated_fields:
                stage_updated_fields.append("updated_at")
            stage_updated_fields.extend(["escalated_at", "escalation_level"])
            escalations_sent += 1
            document_updated = True

        if document_updated:
            with transaction.atomic():
                stage.document.save(update_fields=["metadata", "updated_at"])
                stage.save(update_fields=list(dict.fromkeys(stage_updated_fields)))

    return {
        "checked": active_stages.count(),
        "reminders_sent": reminders_sent,
        "escalations_sent": escalations_sent,
        "notifications_sent": notifications_sent,
        "notification_failures": notification_failures,
    }
